/*
 * sail's C ABI. It only grows: a function, once in a release, never changes
 * its signature or what it means, and a change is a new function
 * (sail_check_config2). There is no version number to compare:
 * sail_capabilities gives the sail release and the modules compiled in, and
 * a call a sail lacks fails with SAIL_ERR_UNSUPPORTED. docs/ffi.md is the
 * contract.
 */

#ifndef SAIL_H
#define SAIL_H

/* Generated by cbindgen from sail-ffi/src: do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Success.
 */
#define SAIL_OK 0

/*
 An argument is null, not UTF-8, or not what the call takes.
 */
#define SAIL_ERR_INVALID_ARGUMENT 1

/*
 The handle is not one sail gave, or it was freed.
 */
#define SAIL_ERR_NO_INSTANCE 2

/*
 The instance is not in a state the call can be made in: it is not
 running, or is starting already.
 */
#define SAIL_ERR_STATE 3

/*
 The configuration, or the settings, do not read or do not build.
 */
#define SAIL_ERR_CONFIG 4

/*
 A system call, a connection or a delay test failed.
 */
#define SAIL_ERR_IO 5

/*
 No outbound, group, member, mode or operation so named.
 */
#define SAIL_ERR_NOT_FOUND 6

/*
 This build of sail, or this instance, does not have what the call
 needs.
 */
#define SAIL_ERR_UNSUPPORTED 7

/*
 The operation was cancelled, or the start was stopped.
 */
#define SAIL_ERR_CANCELLED 8

/*
 The call's time ran out; what it asked for may still happen.
 */
#define SAIL_ERR_TIMEOUT 9

/*
 The call would wait on the thread it was made on: one of the
 instance's own, as a `protect_socket` callback runs on.
 */
#define SAIL_ERR_WRONG_THREAD 10

/*
 sail failed where it should not have; the message says how. A code
 this header does not name, from a newer sail, is taken as this one.
 */
#define SAIL_ERR_INTERNAL 11

/*
 An essential task of the instance panicked, or a lock a panic poisoned
 was met: the instance failed (`"error_kind": "panicked"`).
 */
#define SAIL_ERR_PANICKED 12

/*
 A reload adds, removes or changes what only a start sets up (a TUN):
 nothing changed; stop and start to apply it.
 */
#define SAIL_ERR_NEEDS_RESTART 13

/*
 A TUN's device name is in use: a configured one, or each free name
 sail tried was taken before it opened (a start again may succeed).
 */
#define SAIL_ERR_TUN_NAME_TAKEN 14

/*
 A reload that replaced an inbound on its own address: the new one did
 not bind, and the old one could not listen again; it listens no more.
 */
#define SAIL_ERR_INBOUND_LOST 15

/*
 The instance's state, as `sail_instance_state` gives it: now, then on
 each change.
 */
#define SAIL_EVENT_STATE 1

/*
 The instance's log: `{"reset", "lines": [{"level", "message",
 "time_ms"}], "dropped"}`. Options: `{"level": "info"}` (every level
 when unset), `{"backlog": false}` to leave out the lines kept before.
 `reset` true: drop the lines had so far (the first event, and after a
 `sail_clear_logs`). `dropped`: lines left out since the last event, as
 the callback was too slow for them.
 */
#define SAIL_EVENT_LOG 2

/*
 The traffic, each interval while the instance runs: `{"up", "down"}`
 in bytes a second, `"up_total", "down_total", "connections",
 "memory"`. Options: `{"interval_ms": 1000}`.
 */
#define SAIL_EVENT_STATUS 3

/*
 The connections open, each interval while the instance runs, as
 `sail_connections` gives them. Options: `{"interval_ms": 1000}`.
 */
#define SAIL_EVENT_CONNECTIONS 4

/*
 The outbounds and groups, as `sail_outbounds` gives them, when they
 change: a selection, a delay measured. Options: `{"interval_ms": 250}`,
 how often they are looked at.
 */
#define SAIL_EVENT_OUTBOUNDS 5

/*
 A change of network the connections made on the one before do not
 survive: `{"generation", "reason": "default-interface" |
 "state" | "host" | "wake", "old", "new"}`, the networks as
 `sail_set_network_state` takes them; while the instance runs. In the
 tunnel process only: a command service client's subscription fails with
 SAIL_ERR_UNSUPPORTED, as libbox's apps follow the network there.
 */
#define SAIL_EVENT_NETWORK 6

/*
 A command service client's connection was lost, or the service closed:
 `{"error": why, or null}`, once, the subscription's last event. Its
 release follows.
 */
#define SAIL_EVENT_DISCONNECTED 7

/*
 A task of the instance panicked: `{"task", "class": "contained" |
 "essential", "message", "count"}`, `count` the instance's contained
 panics so far. A contained panic ended that task alone and the instance
 goes on; an essential one failed it, which the state event tells too.
 Through stops and starts; `{"lagged": missed}` when the host fell
 behind and that many are gone. In the tunnel process only.
 */
#define SAIL_EVENT_FAULT 8

/*
 An instance, as the host holds it; 0 is none.
 */
typedef uint64_t SailInstance;

/*
 A delay test running, as the host holds it; 0 is none.
 */
typedef uint64_t SailOperation;

/*
 A subscription, as the host holds it; 0 is none.
 */
typedef uint64_t SailSubscription;

/*
 What the host does for an instance. Every callback may be null; each
 is passed `context`, and may be called from any thread.

 The host sets `struct_size` to `sizeof(SailPlatform)`: callbacks added
 in later versions of this header are then read as null from a host
 built against an earlier one.
 */
typedef struct SailPlatform {
  uint32_t struct_size;
  /*
   The host's, passed to every callback.
   */
  void *context;
  /*
   Called once, when sail no longer calls any callback of this
   platform: after the instance is freed and has stopped. From any
   thread.
   */
  void (*release)(void *context);
  /*
   Keeps the outbound socket `fd` out of the host's VPN, before it
   connects (Android's `VpnService.protect`); returns whether it did.
   Called on the instance's threads, as it dials: it must not wait on
   sail, whose waiting calls fail there with SAIL_ERR_WRONG_THREAD.
   */
  bool (*protect_socket)(int32_t fd, void *context);
  /*
   Opens the TUN device a TUN inbound asks for (Android's
   `VpnService.Builder.establish`, iOS's packet flow's utun), as the
   JSON `request` says: `interface_name`, `mtu`, `ipv4` and `ipv6` (an
   address with its prefix, or null), `auto_route`, and for Android
   `include_package` and `exclude_package`, which the host applies with
   `addAllowedApplication` / `addDisallowedApplication` (sail refuses a
   configuration with uid or `include_android_user` options, which a
   VpnService cannot apply, as sing-box's libbox does).
   Returns the device's file descriptor, which the instance then owns,
   or a negative number. With it, the host routes the device: sail
   changes no routes. Called while the instance starts, on the thread
   that starts it.
   */
  int32_t (*open_tun)(const char *request, void *context);
  /*
   Stops the instance as the host does, when a command service client
   asks (libbox's `ServiceStop`): the host tells its system (iOS stops
   the Network Extension) and stops the instance. Returns a SAIL_*
   code. Called on a thread of the command service's own; it may call
   any sail function. Null: sail stops the instance itself.
   */
  int32_t (*service_stop)(void *context);
  /*
   Reloads the instance as the host does, when a client asks (libbox's
   `ServiceReload`), as `service_stop` is called. Null: sail reloads
   it from its file.
   */
  int32_t (*service_reload)(void *context);
  /*
   Who opened a connection (Android: `ConnectivityManager.
   getConnectionOwnerUid`, then `PackageManager.getPackagesForUid`).
   With it, every connection is asked about before it is routed, as
   sing-box's libbox does on Android, and the rules `package_name`,
   `package_name_regex`, `user` and `user_id` match.

   `query` is JSON: `{"network": "tcp" | "udp", "source": "ip:port",
   "destination": "host:port"}`. The host writes `{"uid", "user" (or
   null), "packages": [...]}` into `out`, at most `out_len` bytes,
   and returns how many it wrote; 0 when it cannot tell; when `out_len`
   is too small, minus the length it needs, and it is called again
   with that much. Called on the instance's threads, as it routes: it
   must not wait on sail.
   */
  ptrdiff_t (*find_connection_owner)(const char *query, char *out, size_t out_len, void *context);
} SailPlatform;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Frees a string sail returned. Null is ignored.

 @param s The string; not to be used after.
 */
void sail_free_string(char *s);

/*
 What this build of sail is, as JSON: `{"version", "commit", "features":
 ["inbound-tun", "outbound-vless", …]}`, the release, the commit it was
 built from (a short hash, or "unknown"), and the modules compiled in. The features say what was built, not which functions or
 fields there are: there is no version number to compare (see the
 header's contract).

 @param out Takes the JSON, the host's to free.
 @param err Takes the message of a failure, or null.
 */
int32_t sail_capabilities(char **out,
                          char **err);

/*
 What the instance sent and received, as JSON: `{"up_total",
 "down_total", "connections", "memory"}`.
 */
int32_t sail_traffic(SailInstance instance, char **out, char **err);

/*
 The connections open, as JSON: `{"connections": [{"id", "network",
 "inbound_type", "inbound_tag", "source", "destination", "host",
 "process", "user", "upload", "download", "start", "chains", "rule"}]}`,
 by id.
 */
int32_t sail_connections(SailInstance instance, char **out, char **err);

/*
 Closes the connection `id`: its reads and writes fail.

 @param closed Takes whether there was one so numbered; may be null.
 */
int32_t sail_close_connection(SailInstance instance, uint64_t id, bool *closed, char **err);

/*
 Closes every connection open.

 @param count Takes how many; may be null.
 */
int32_t sail_close_all_connections(SailInstance instance, uint64_t *count, char **err);

/*
 The outbounds, members of outbound providers too, as JSON:
 `{"outbounds": [{"tag", "kind" (Mihomo's type name), "protocol"
 (sing-box's, null for a provider's member), "provider", "udp",
 "history": [{"time_ms", "delay_ms" (null for a failure)}], "group":
 {"selected", "members", "selectable"} or null}]}`, in the
 configuration's order.
 */
int32_t sail_outbounds(SailInstance instance, char **out, char **err);

/*
 The groups: the outbounds that select among members, as
 `sail_outbounds` gives them.
 */
int32_t sail_groups(SailInstance instance, char **out, char **err);

/*
 Selects `member` of the selector `group`; the choice is kept in the
 cache file, as sing-box keeps it. A fallback is pinned to `member`
 instead, as Mihomo pins it: it goes there while the member is up.

 @return SAIL_ERR_NOT_FOUND with no such group; SAIL_ERR_INVALID_ARGUMENT
     when it is neither a selector nor a fallback, or has no such member.
 */
int32_t sail_select(SailInstance instance, const char *group, const char *member, char **err);

/*
 The outbound providers, as JSON: `{"providers": [{"tag", "source":
 "remote" | "local" | "inline", "members", "updated_ms",
 "next_update_ms" (null when it is not updated by itself), "failure":
 {"at_ms", "error"} (the last update's, null after a success),
 "subscription": {"upload", "download", "total", "expire_ms"} (what the
 server says of it, or null)}]}`, in the configuration's order. No URL:
 a subscription's carries its token. Their members are among
 `sail_outbounds`, with their `provider`.
 */
int32_t sail_providers(SailInstance instance, char **out, char **err);

/*
 Downloads the outbound provider `tag` again, or reads its file again,
 and waits until its members are in place.

 @return SAIL_ERR_NOT_FOUND with no such provider; SAIL_ERR_IO when the
     update failed, which `sail_providers` then tells too;
     SAIL_ERR_STATE when the instance is stopping.
 */
int32_t sail_update_provider(SailInstance instance, const char *tag, char **err);

/*
 The rule-sets, as JSON: `{"rule_sets": [{"tag", "source": "remote" |
 "local" | "inline", "format", "behavior", "rules", "updated_ms",
 "next_update_ms", "failure": {"at_ms", "error"}}]}`, by tag.
 */
int32_t sail_rule_sets(SailInstance instance, char **out, char **err);

/*
 Downloads the remote rule-set `tag` again and waits until its rules are
 in place; a local or inline one is as it is.

 @return SAIL_ERR_NOT_FOUND with no such rule-set; SAIL_ERR_IO when the
     update failed; SAIL_ERR_STATE when the instance is stopping.
 */
int32_t sail_update_rule_set(SailInstance instance, const char *tag, char **err);

/*
 Connects to `host`:`port` through the outbound `outbound` alone,
 whatever the rules say, and waits until it is connected: the outbound's
 handshake done. The connection is counted and listed as one of its own,
 its inbound `control`, until it ends.

 @param network `tcp` or `udp`.
 @param fd Takes one end of a socket pair that sail relays through the
     outbound: the host's to own, read, write and close; closing it ends
     the connection. TCP: a stream. UDP: one message per datagram, both
     ways, to and from `host`:`port` alone; SOCK_SEQPACKET on Linux and
     Android, SOCK_DGRAM on Apple's systems, each end's buffers 256 KiB.
 @return SAIL_ERR_NOT_FOUND with no such outbound; SAIL_ERR_TIMEOUT
     when `timeout_ms` passed first; SAIL_ERR_IO when the outbound
     failed to connect; SAIL_ERR_STATE when the instance does not run;
     SAIL_ERR_UNSUPPORTED through a command service client (a descriptor
     does not cross processes) and on Windows.
 */
int32_t sail_dial(SailInstance instance,
                  const char *outbound,
                  const char *network,
                  const char *host,
                  uint16_t port,
                  uint32_t timeout_ms,
                  int32_t *fd,
                  char **err);

/*
 Measures the delay of the outbound `tag` now, with an HTTP request to
 `url` (sing-box's default when null), and waits for it; it is kept among
 the outbound's delays, a failure too.

 @param delay_ms Takes the delay, in milliseconds.
 @return SAIL_ERR_IO when the request failed; SAIL_ERR_TIMEOUT.
 */
int32_t sail_delay(SailInstance instance,
                   const char *tag,
                   const char *url,
                   uint32_t timeout_ms,
                   uint64_t *delay_ms,
                   char **err);

/*
 Measures delays without waiting, as sing-box's apps do: of the outbound
 `tag`, or of each member of the group `tag`. Each is kept among the
 outbound's delays, which `sail_outbounds` and the outbounds events tell.

 @param operation Takes the test's handle, for `sail_cancel`; may be
     null. Through a command service client, it takes 0: a test there is
     not cancelled.
 */
int32_t sail_url_test(SailInstance instance,
                      const char *tag,
                      const char *url,
                      uint32_t timeout_ms,
                      SailOperation *operation,
                      char **err);

/*
 Cancels a delay test `sail_url_test` started.

 @return SAIL_ERR_NOT_FOUND when it has ended.
 */
int32_t sail_cancel(SailOperation operation, char **err);

/*
 The mode rules match and the modes they name, as JSON: `{"mode",
 "modes"}`. An instance has modes though its configuration has no Clash
 API, as libbox's apps do: `Rule`, unless the cache file kept another.
 */
int32_t sail_mode(SailInstance instance, char **out, char **err);

/*
 Switches the mode to `mode`, matched as it is, then in any case, among
 the modes; kept in the cache file.

 @return SAIL_ERR_NOT_FOUND for a mode not among them.
 */
int32_t sail_set_mode(SailInstance instance, const char *mode, char **err);

/*
 Tells the running instance what network the host is on, whenever it
 changes: the rules on the network (`wifi_ssid`, `network_type`, …) and
 the `network` groups match it. Once told, sail's own detection is left.
 The tunnel process's host tells it, as libbox's does: not a client.

 @param state JSON: `{"type": "wifi" | "cellular" | "ethernet" |
     "other", "interface", "ssid", "bssid", "gateway", "addresses":
     ["192.168.1.2/24"], "mcc_mnc", "expensive", "constrained",
     "captive", "interfaces"}`, every field optional. `captive`: behind a
     captive portal, as the host says; every connection then goes
     straight out, whatever the rules say, until it clears.
     `interfaces`: every interface sail may dial out of, the default's
     among them, each `{"name", "type", "addresses", "expensive",
     "constrained"}`, for a connection's choice of network
     (`network_strategy`); the fields above describe the default network
     and are what the rules go by.
 @return SAIL_ERR_CONFIG for a state that does not read.
 */
int32_t sail_set_network_state(SailInstance instance, const char *state, char **err);

/*
 Tells the TUN inbound that the host's network changed, as after a
 switch between Wi-Fi and cellular: flows of the previous network are
 reset, and new ones start on the current one. The tunnel process's
 host tells it: not a client.

 @param mtu The interface's new MTU, or 0 to keep it.
 @return SAIL_ERR_CONFIG when there is no TUN inbound.
 */
int32_t sail_network_changed(SailInstance instance, uint16_t mtu, char **err);

/*
 Forgets the lines of the instance's log kept; its log subscriptions are
 sent `reset`.
 */
int32_t sail_clear_logs(SailInstance instance, char **err);

/*
 What the running instance does and needs, as JSON: `{"has_tun",
 "opens_tun" (the host opens its device), "protects_sockets",
 "needs_network" (the host should tell it the network), "has_modes"}`.
 */
int32_t sail_instance_capabilities(SailInstance instance, char **out, char **err);

/*
 Follows what `kind` names of the instance: `callback` is called with
 each event, on the instance's events thread, in order, one at a time.
 A slow callback delays only its instance's events: a status or the
 connections are then sent less often, log lines left out and counted.
 A callback may call any sail function, for this instance too.

 @param options JSON, the kind's options, or null.
 @param context Passed to `callback` and `release`.
 @param release Called once, on the events thread or the one ending the
     subscription, after the last event: when unsubscribed, or the
     instance freed. Null for none. When the call fails, sail keeps
     nothing of `context` and never calls it.
 @param out Takes the subscription's handle.
 @return SAIL_ERR_UNSUPPORTED for a kind this build does not follow.
 */
int32_t sail_subscribe(SailInstance instance,
                       uint32_t kind,
                       const char *options,
                       void (*callback)(uint32_t kind, const char *json, void *context),
                       void *context,
                       void (*release)(void *context),
                       SailSubscription *out,
                       char **err);

/*
 Ends a subscription. Once it returns, its callback is not called again,
 and its release has been called, but on the instance's events thread
 (from a callback), where the callback running returns first, and the
 release follows. A callback that waits on a lock the thread calling
 this holds would wait for ever: don't.

 @return SAIL_ERR_NO_INSTANCE for a subscription ended already, or its
     instance freed.
 */
int32_t sail_unsubscribe(SailSubscription subscription, char **err);

/*
 Makes an instance, idle until started.

 @param settings JSON, or null for the defaults: the core's
     (`{"profile": "mobile", "set": ["relay.buffer_size=32"], "data_dir",
     "cache_dir", "log_to_system", "socket_protect", "sub_store"}`; on
     iOS and Android the "mobile" profile and the system log unless
     said), and the FFI's: `log_lines`, the lines of its log kept
     (3000), `worker_threads`, 0 or unset for one thread,
     `stack_size` of each worker, in bytes, and `stop_within_ms`, how
     long a stop waits for the instance's tasks to end (2000).
 @param platform What the host does for it, or null for nothing; read
     during the call, its callbacks kept until `release`.
 @param out Takes the instance's handle.
 @param err Takes the message of a failure, or null.
 */
int32_t sail_instance_new(const char *settings,
                          const struct SailPlatform *platform,
                          SailInstance *out,
                          char **err);

/*
 Starts the instance with the configuration `config`, in any format sail
 reads (sing-box's JSON, Clash's YAML, a Surge profile). Returns once it
 runs, or failed; it runs on a thread of its own until stopped.

 @param err Takes why it did not start, or null.
 @return SAIL_ERR_STATE when it is starting or running already;
     SAIL_ERR_CANCELLED when stopped while it started.
 */
int32_t sail_instance_start(SailInstance instance, const char *config, char **err);

/*
 Starts the instance as `sail_instance_start` does, from the file at
 `path`, in the format its extension names; a reload without a
 configuration reads it again.
 */
int32_t sail_instance_start_file(SailInstance instance, const char *path, char **err);

/*
 Reloads the running instance with `config`, or, when null, from the
 file it was started from. What did not change goes on: connections,
 selections, the delays measured. A reload that fails leaves the
 instance as it was.
 */
int32_t sail_instance_reload(SailInstance instance, const char *config, char **err);

/*
 `sail_instance_reload`, telling what it did, as JSON: `{"path": "full" |
 "inbounds_only", "inbounds": [{"tag", "change": "untouched" |
 "reloaded" | "added" | "removed" | "replaced"}], "notes": [{"kind":
 "endpoint_keeps_defaults", "text", "endpoint", "options"}]}`. Only the
 inbounds removed and replaced had their connections closed; with
 `inbounds_only`, the outbounds, groups, DNS and routing, and what they
 held, are those that ran. A reload that fails tells nothing and leaves
 the instance as it was.

 @return SAIL_ERR_NEEDS_RESTART when it adds, removes or changes what
     only a start sets up (a TUN); SAIL_ERR_INBOUND_LOST when an inbound
     it was to replace on its own address listens no more;
     SAIL_ERR_UNSUPPORTED through a command service client.
 */
int32_t sail_instance_reload_report(SailInstance instance,
                                    const char *config,
                                    char **out,
                                    char **err);

/*
 Stops the instance, and waits up to `timeout_ms` for it to have
 stopped; 0 asks without waiting. A stop while it starts ends the
 start. Stopping one not running does nothing. Called on a thread of
 the instance's own (in `protect_socket` or `open_tun`), it asks
 without waiting.

 @return SAIL_OK once stopped, or asked; SAIL_ERR_TIMEOUT if it is still
     stopping.
 */
int32_t sail_instance_stop(SailInstance instance, uint32_t timeout_ms, char **err);

/*
 Frees the instance: the handle names nothing from now on. It is asked
 to stop, without waiting, and its subscriptions end, each context
 released. The platform's `release` is called once it has stopped and
 sail calls none of its callbacks any more. Freeing a handle freed, or
 0, does nothing.
 */
void sail_instance_free(SailInstance instance);

/*
 Serves the instance to the app's other processes, as libbox's command
 server does: a client (`sail_client_connect`) there then answers the
 same calls as the instance. It serves while the instance is idle or
 failed too, until freed, or this is called again; null `options`
 stops serving.

 @param options JSON: `{"path"}`, a unix socket (an iOS app's group
     container's, an Android app's files directory's), made readable
     and writable by the app's user only, a stale file there replaced,
     the path at most 103 bytes on Darwin and 107 on Linux, on Unix
     only; or `{"port", "secret"}`, loopback TCP, every call carrying
     the secret (32 characters at least, as `sail generate secret`
     makes), the only one on Windows.
 @return SAIL_ERR_STATE when a service answers at the path already;
     SAIL_ERR_CONFIG for options that do not read; SAIL_ERR_UNSUPPORTED
     in a build without the command service, or for a path on
     Windows.
 */
int32_t sail_instance_serve(SailInstance instance, const char *options, char **err);

/*
 Connects to the command service an instance serves in another process
 (`sail_instance_serve`), as libbox's command client does: the handle
 answers the same calls an instance's does, and is freed with
 `sail_instance_free`. A client does not reconnect: when the connection
 is lost, its calls fail, and each subscription gets one
 SAIL_EVENT_DISCONNECTED; the host connects again.

 @param options JSON: `{"path"}`, `{"port", "secret"}`, or `{"fd"}`, a
     connected socket the host has (a macOS system extension's, passed
     over XPC), which the client owns from then on. `{"path"}` and
     `{"fd"}` are Unix only: on Windows only `{"port", "secret"}`.
 @param out Takes the client's handle.
 @return SAIL_ERR_IO when no service answers; SAIL_ERR_UNSUPPORTED in a
     build without the command service, or for a path or descriptor on
     Windows.
 */
int32_t sail_client_connect(const char *options, SailInstance *out, char **err);

/*
 The instance's state, as JSON: `{"state": "idle" | "starting" |
 "running" | "stopping" | "stopped" | "failed", "error": why it failed,
 or null, "error_kind": the failure's kind (`panicked`, `config`,
 `tun_name_taken`, ...), or null, "left": what the failed run's teardown
 left in the system, as `sail_instance_stop_report` gives it (empty when
 nothing is), "started_at_ms": when it last started running, or null}`.
 */
int32_t sail_instance_state(SailInstance instance, char **out, char **err);

/*
 What the instance's last stop, or the end of its last run, could not
 end or undo, as JSON: `{"tasks": [{"name", "count"}], "waited_ms",
 "left": [{"kind": "tun" | "route" | "rule" | "dns" | "nft" | "wfp" |
 "file" | "task", "resource", "why", "clear": the command that clears
 it by hand, or null}]}`; `null` before any stop. A failed or stopped
 instance's is kept until it starts again.

 @return SAIL_ERR_UNSUPPORTED through a command service client.
 */
int32_t sail_instance_stop_report(SailInstance instance, char **out, char **err);

/*
 Checks the configuration file at `path`: it reads and builds, as an
 instance with `settings` would start it, without starting.

 @param settings The instance's settings, or null.
 @param out Takes JSON, or null for none: `{"warnings": [...]}`, what a
     start would warn of (fields sail ignores, deprecated ones, what
     building it logged as a warning), as `sail -T` prints them.
 @param err Takes what is wrong with it, or null.
 */
int32_t sail_check_config(const char *path, const char *settings, char **out, char **err);

/*
 Reads share links into sing-box outbounds.

 @param input A share link, or a subscription: base64, or a link a line.
 @param out Takes JSON: `{"outbounds": [...], "warnings": [...]}`, an
     outbound for each link read and a warning for each line that is not
     one (no warning holds a password, a UUID or a key).
 */
int32_t sail_import_share_links(const char *input, char **out, char **err);

/*
 The data files (assets) the configuration at `path` reads: `asn.mmdb`,
 `geo.mmdb`, `site.dat`, or files it names. sail downloads none: the
 host fetches the missing ones into the data directory.

 @param settings The instance's settings (its `data_dir` places the
     files), or null.
 @param out Takes JSON: `{"assets": [{"name", "kind" ("mmdb" or
     "site"), "path", "used_by": [the fields that read it],
     "present"}]}`.
 */
int32_t sail_required_assets(const char *path, const char *settings, char **out, char **err);

/*
 Tests each outbound of the configuration `config` (its text) through,
 without an instance: TCP and UDP, as sail's health check does. Returns
 when every one is tested; `callback` is called on the calling thread,
 once for each, as it is tested.

 @param concurrency How many at once.
 @param timeout_ms For each test; 0 for no limit.
 */
int32_t sail_test_outbounds(const char *config,
                            const char *settings,
                            uint32_t concurrency,
                            uint32_t timeout_ms,
                            void (*callback)(const char *tag,
                                             int32_t tcp_ms,
                                             int32_t udp_ms,
                                             void *context),
                            void *context,
                            char **err);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SAIL_H */
