//! Generates the command service's Rust from its proto: run from the
//! repository's root, or anywhere with the manifest path.

use std::path::Path;

fn main() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let proto = root.join("sail-ffi/proto");
    let out = root.join("sail-ffi/src/command");
    let protoc = protoc_bin_vendored::protoc_bin_path().expect("protoc");
    std::env::set_var("PROTOC", protoc);
    let generated = tempdir();
    tonic_prost_build::configure()
        .build_server(true)
        .build_client(true)
        .out_dir(&generated)
        .compile_protos(&[proto.join("command.proto")], &[proto])
        .expect("the proto does not compile");
    let code = std::fs::read_to_string(generated.join("sail.command.v1.rs")).expect("generated");
    std::fs::write(
        out.join("proto.rs"),
        format!(
            "// Generated by tools/command-proto from sail-ffi/proto/command.proto: do not\n\
             // edit.\n#![allow(clippy::all, missing_docs)]\n\n{}",
            code
        ),
    )
    .expect("written");
    std::fs::remove_dir_all(&generated).ok();
    println!("wrote {}", out.join("proto.rs").display());
}

fn tempdir() -> std::path::PathBuf {
    let dir = std::env::temp_dir().join(format!("sail-command-proto-{}", std::process::id()));
    std::fs::create_dir_all(&dir).expect("temp dir");
    dir
}
