// The examples page of the configuration reference: the configurations in
// website/examples, each with its title and introduction from
// examples/index.json, and each checked against the schema. Pure.

import { frontmatter } from './reference.mjs';
import { validate } from './schema.mjs';

const WORDS = {
  en: {
    title: 'Examples',
    description: 'Whole configurations of sail, each checked by sail and by the schema.',
    intro: 'Generated by `website/scripts/build-config.mjs` from `website/examples`; do not edit. Each configuration is read and built by sail without a warning (`sail/tests/it/test_examples.rs`) and is valid by the [JSON schema](/sail/schema.json). Names, keys and passwords are placeholders.',
  },
  zh: {
    title: '示例',
    description: 'sail 的完整配置示例，均经 sail 与 schema 校验。',
    intro: '本页由 `website/scripts/build-config.mjs` 依据 `website/examples` 生成，请勿手改。每份配置都经 sail 读取并构建、没有警告（`sail/tests/it/test_examples.rs`），并符合 [JSON schema](/sail/schema.json)。其中的域名、密钥与密码均为占位。',
  },
};

/** `{ 'reference/examples.md': text, 'zh/reference/examples.md': text }`
 * from the index and the files' texts, by file name. */
export function examplePages(index, texts, schema) {
  const problems = [];
  for (const e of index) {
    if (!(e.file in texts)) problems.push(`${e.file}: listed, and not there`);
    else for (const p of validate(schema, JSON.parse(texts[e.file]))) problems.push(`${e.file}: ${p}`);
  }
  for (const file of Object.keys(texts)) if (!index.some(e => e.file === file)) problems.push(`${file}: not in examples/index.json`);
  if (problems.length) throw new Error(`Examples:\n${problems.join('\n')}`);
  const files = {};
  for (const lang of ['en', 'zh']) {
    const w = WORDS[lang];
    let body = `${frontmatter(w.title, w.description)}${w.intro}\n\n`;
    for (const e of index) body += `## ${e.title[lang]}\n\n${e.intro[lang]}\n\n\`${e.file}\`\n\n\`\`\`json\n${texts[e.file].trimEnd()}\n\`\`\`\n\n`;
    files[`${lang === 'zh' ? 'zh/' : ''}reference/examples.md`] = body;
  }
  return files;
}
