// Generated by tools/command-proto from sail-ffi/proto/command.proto: do not
// edit.
#![allow(clippy::all, missing_docs)]

// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Version {
    #[prost(uint32, tag = "1")]
    pub api_version: u32,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub features: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Of the instance, while it runs.
    #[prost(bool, tag = "4")]
    pub has_tun: bool,
    #[prost(bool, tag = "5")]
    pub opens_tun: bool,
    #[prost(bool, tag = "6")]
    pub protects_sockets: bool,
    #[prost(bool, tag = "7")]
    pub needs_network: bool,
    #[prost(bool, tag = "8")]
    pub has_modes: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServiceStatus {
    /// idle, starting, running, stopping, stopped, failed
    #[prost(string, tag = "1")]
    pub state: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "3")]
    pub started_at_ms: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscribeLogRequest {
    /// trace, debug, info, warn, error; every level when empty.
    #[prost(string, tag = "1")]
    pub level: ::prost::alloc::string::String,
    /// Leave out the lines kept before.
    #[prost(bool, tag = "2")]
    pub no_backlog: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogLine {
    #[prost(string, tag = "1")]
    pub level: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub time_ms: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bool, tag = "1")]
    pub reset: bool,
    #[prost(message, repeated, tag = "2")]
    pub lines: ::prost::alloc::vec::Vec<LogLine>,
    #[prost(uint64, tag = "3")]
    pub dropped: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IntervalRequest {
    /// 0 for the default.
    #[prost(uint64, tag = "1")]
    pub interval_ms: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Traffic {
    #[prost(uint64, tag = "1")]
    pub up_total: u64,
    #[prost(uint64, tag = "2")]
    pub down_total: u64,
    #[prost(uint64, tag = "3")]
    pub connections: u64,
    #[prost(uint64, tag = "4")]
    pub memory: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Status {
    #[prost(uint64, tag = "1")]
    pub up: u64,
    #[prost(uint64, tag = "2")]
    pub down: u64,
    #[prost(uint64, tag = "3")]
    pub up_total: u64,
    #[prost(uint64, tag = "4")]
    pub down_total: u64,
    #[prost(uint64, tag = "5")]
    pub connections: u64,
    #[prost(uint64, tag = "6")]
    pub memory: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Connection {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub network: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub inbound_type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub inbound_tag: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub destination: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "7")]
    pub host: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub process: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "9")]
    pub user: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, tag = "10")]
    pub upload: u64,
    #[prost(uint64, tag = "11")]
    pub download: u64,
    #[prost(uint32, tag = "12")]
    pub start: u32,
    #[prost(string, repeated, tag = "13")]
    pub chains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "14")]
    pub rule: ::core::option::Option<::prost::alloc::string::String>,
    /// Who opened it, as the host tells it (Android).
    #[prost(uint32, optional, tag = "15")]
    pub uid: ::core::option::Option<u32>,
    #[prost(string, repeated, tag = "16")]
    pub packages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Connections {
    #[prost(message, repeated, tag = "1")]
    pub connections: ::prost::alloc::vec::Vec<Connection>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConnectionEvent {
    #[prost(enumeration = "connection_event::Type", tag = "1")]
    pub r#type: i32,
    #[prost(uint64, tag = "2")]
    pub id: u64,
    /// For NEW.
    #[prost(message, optional, tag = "3")]
    pub connection: ::core::option::Option<Connection>,
    /// For UPDATE: what it sent and received since the last.
    #[prost(uint64, tag = "4")]
    pub upload_delta: u64,
    #[prost(uint64, tag = "5")]
    pub download_delta: u64,
}
/// Nested message and enum types in `ConnectionEvent`.
pub mod connection_event {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Type {
        New = 0,
        Update = 1,
        Closed = 2,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::New => "NEW",
                Self::Update => "UPDATE",
                Self::Closed => "CLOSED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NEW" => Some(Self::New),
                "UPDATE" => Some(Self::Update),
                "CLOSED" => Some(Self::Closed),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectionEvents {
    /// Drop the connections had so far: those that follow are all.
    #[prost(bool, tag = "1")]
    pub reset: bool,
    #[prost(message, repeated, tag = "2")]
    pub events: ::prost::alloc::vec::Vec<ConnectionEvent>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseConnectionRequest {
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseConnectionReply {
    #[prost(bool, tag = "1")]
    pub closed: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseAllConnectionsReply {
    #[prost(uint64, tag = "1")]
    pub count: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Delay {
    #[prost(uint64, tag = "1")]
    pub time_ms: u64,
    /// Absent for a test that failed.
    #[prost(uint64, optional, tag = "2")]
    pub delay_ms: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Group {
    #[prost(string, tag = "1")]
    pub selected: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub members: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "3")]
    pub selectable: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Outbound {
    #[prost(string, tag = "1")]
    pub tag: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub protocol: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub provider: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag = "5")]
    pub udp: bool,
    #[prost(message, repeated, tag = "6")]
    pub history: ::prost::alloc::vec::Vec<Delay>,
    #[prost(message, optional, tag = "7")]
    pub group: ::core::option::Option<Group>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OutboundsRequest {
    /// The groups only.
    #[prost(bool, tag = "1")]
    pub groups: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Outbounds {
    #[prost(message, repeated, tag = "1")]
    pub outbounds: ::prost::alloc::vec::Vec<Outbound>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SelectOutboundRequest {
    #[prost(string, tag = "1")]
    pub group: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub member: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UrlTestRequest {
    #[prost(string, tag = "1")]
    pub tag: ::prost::alloc::string::String,
    /// sing-box's default when empty.
    #[prost(string, tag = "2")]
    pub url: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub timeout_ms: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DelayReply {
    #[prost(uint64, tag = "1")]
    pub delay_ms: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClashModeStatus {
    #[prost(string, repeated, tag = "1")]
    pub modes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "2")]
    pub mode: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClashMode {
    #[prost(string, tag = "1")]
    pub mode: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Warnings {
    #[prost(string, repeated, tag = "1")]
    pub warnings: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Generated client implementations.
pub mod started_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    /// The instance, as the C ABI's control functions see it.
    #[derive(Debug, Clone)]
    pub struct StartedClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl StartedClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> StartedClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> StartedClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<http::Request<tonic::body::Body>>>::Error:
                Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            StartedClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// The API version, sail's, and what the instance can do.
        pub async fn get_version(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Version>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/sail.command.v1.Started/GetVersion");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sail.command.v1.Started", "GetVersion"));
            self.inner.unary(req, path, codec).await
        }
        /// The state: now, then on each change.
        pub async fn subscribe_service_status(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ServiceStatus>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sail.command.v1.Started/SubscribeServiceStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "sail.command.v1.Started",
                "SubscribeServiceStatus",
            ));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn get_service_status(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::ServiceStatus>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/sail.command.v1.Started/GetServiceStatus");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "sail.command.v1.Started",
                "GetServiceStatus",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// The log: the lines kept (reset), then lines as they are logged.
        pub async fn subscribe_log(
            &mut self,
            request: impl tonic::IntoRequest<super::SubscribeLogRequest>,
        ) -> std::result::Result<tonic::Response<tonic::codec::Streaming<super::Log>>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/sail.command.v1.Started/SubscribeLog");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sail.command.v1.Started", "SubscribeLog"));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn clear_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/sail.command.v1.Started/ClearLogs");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sail.command.v1.Started", "ClearLogs"));
            self.inner.unary(req, path, codec).await
        }
        /// The traffic, each interval while the instance runs.
        pub async fn subscribe_status(
            &mut self,
            request: impl tonic::IntoRequest<super::IntervalRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Status>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/sail.command.v1.Started/SubscribeStatus");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "sail.command.v1.Started",
                "SubscribeStatus",
            ));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn get_traffic(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Traffic>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/sail.command.v1.Started/GetTraffic");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sail.command.v1.Started", "GetTraffic"));
            self.inner.unary(req, path, codec).await
        }
        /// The connections: those open (reset), then what changed, each interval.
        pub async fn subscribe_connections(
            &mut self,
            request: impl tonic::IntoRequest<super::IntervalRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ConnectionEvents>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sail.command.v1.Started/SubscribeConnections",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "sail.command.v1.Started",
                "SubscribeConnections",
            ));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn get_connections(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Connections>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/sail.command.v1.Started/GetConnections");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sail.command.v1.Started", "GetConnections"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn close_connection(
            &mut self,
            request: impl tonic::IntoRequest<super::CloseConnectionRequest>,
        ) -> std::result::Result<tonic::Response<super::CloseConnectionReply>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/sail.command.v1.Started/CloseConnection");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "sail.command.v1.Started",
                "CloseConnection",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn close_all_connections(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::CloseAllConnectionsReply>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sail.command.v1.Started/CloseAllConnections",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "sail.command.v1.Started",
                "CloseAllConnections",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// The outbounds and groups: now, then when they change.
        pub async fn subscribe_outbounds(
            &mut self,
            request: impl tonic::IntoRequest<super::IntervalRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Outbounds>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/sail.command.v1.Started/SubscribeOutbounds");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "sail.command.v1.Started",
                "SubscribeOutbounds",
            ));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn get_outbounds(
            &mut self,
            request: impl tonic::IntoRequest<super::OutboundsRequest>,
        ) -> std::result::Result<tonic::Response<super::Outbounds>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/sail.command.v1.Started/GetOutbounds");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sail.command.v1.Started", "GetOutbounds"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn select_outbound(
            &mut self,
            request: impl tonic::IntoRequest<super::SelectOutboundRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/sail.command.v1.Started/SelectOutbound");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sail.command.v1.Started", "SelectOutbound"));
            self.inner.unary(req, path, codec).await
        }
        /// Measures without waiting; the delays come in the outbounds.
        pub async fn url_test(
            &mut self,
            request: impl tonic::IntoRequest<super::UrlTestRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/sail.command.v1.Started/URLTest");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sail.command.v1.Started", "URLTest"));
            self.inner.unary(req, path, codec).await
        }
        /// Measures one outbound, and waits.
        pub async fn delay(
            &mut self,
            request: impl tonic::IntoRequest<super::UrlTestRequest>,
        ) -> std::result::Result<tonic::Response<super::DelayReply>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/sail.command.v1.Started/Delay");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sail.command.v1.Started", "Delay"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_clash_mode_status(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::ClashModeStatus>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/sail.command.v1.Started/GetClashModeStatus");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "sail.command.v1.Started",
                "GetClashModeStatus",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn subscribe_clash_mode(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ClashMode>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/sail.command.v1.Started/SubscribeClashMode");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "sail.command.v1.Started",
                "SubscribeClashMode",
            ));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn set_clash_mode(
            &mut self,
            request: impl tonic::IntoRequest<super::ClashMode>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/sail.command.v1.Started/SetClashMode");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sail.command.v1.Started", "SetClashMode"));
            self.inner.unary(req, path, codec).await
        }
        /// What the configuration sets that sail ignores or that is deprecated;
        /// read once, then gone.
        pub async fn get_deprecated_warnings(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Warnings>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/sail.command.v1.Started/GetDeprecatedWarnings",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "sail.command.v1.Started",
                "GetDeprecatedWarnings",
            ));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod started_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with StartedServer.
    #[async_trait]
    pub trait Started: std::marker::Send + std::marker::Sync + 'static {
        /// The API version, sail's, and what the instance can do.
        async fn get_version(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Version>, tonic::Status>;
        /// Server streaming response type for the SubscribeServiceStatus method.
        type SubscribeServiceStatusStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ServiceStatus, tonic::Status>,
            > + std::marker::Send
            + 'static;
        /// The state: now, then on each change.
        async fn subscribe_service_status(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<Self::SubscribeServiceStatusStream>, tonic::Status>;
        async fn get_service_status(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::ServiceStatus>, tonic::Status>;
        /// Server streaming response type for the SubscribeLog method.
        type SubscribeLogStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Log, tonic::Status>,
            > + std::marker::Send
            + 'static;
        /// The log: the lines kept (reset), then lines as they are logged.
        async fn subscribe_log(
            &self,
            request: tonic::Request<super::SubscribeLogRequest>,
        ) -> std::result::Result<tonic::Response<Self::SubscribeLogStream>, tonic::Status>;
        async fn clear_logs(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
        /// Server streaming response type for the SubscribeStatus method.
        type SubscribeStatusStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Status, tonic::Status>,
            > + std::marker::Send
            + 'static;
        /// The traffic, each interval while the instance runs.
        async fn subscribe_status(
            &self,
            request: tonic::Request<super::IntervalRequest>,
        ) -> std::result::Result<tonic::Response<Self::SubscribeStatusStream>, tonic::Status>;
        async fn get_traffic(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Traffic>, tonic::Status>;
        /// Server streaming response type for the SubscribeConnections method.
        type SubscribeConnectionsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ConnectionEvents, tonic::Status>,
            > + std::marker::Send
            + 'static;
        /// The connections: those open (reset), then what changed, each interval.
        async fn subscribe_connections(
            &self,
            request: tonic::Request<super::IntervalRequest>,
        ) -> std::result::Result<tonic::Response<Self::SubscribeConnectionsStream>, tonic::Status>;
        async fn get_connections(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Connections>, tonic::Status>;
        async fn close_connection(
            &self,
            request: tonic::Request<super::CloseConnectionRequest>,
        ) -> std::result::Result<tonic::Response<super::CloseConnectionReply>, tonic::Status>;
        async fn close_all_connections(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::CloseAllConnectionsReply>, tonic::Status>;
        /// Server streaming response type for the SubscribeOutbounds method.
        type SubscribeOutboundsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Outbounds, tonic::Status>,
            > + std::marker::Send
            + 'static;
        /// The outbounds and groups: now, then when they change.
        async fn subscribe_outbounds(
            &self,
            request: tonic::Request<super::IntervalRequest>,
        ) -> std::result::Result<tonic::Response<Self::SubscribeOutboundsStream>, tonic::Status>;
        async fn get_outbounds(
            &self,
            request: tonic::Request<super::OutboundsRequest>,
        ) -> std::result::Result<tonic::Response<super::Outbounds>, tonic::Status>;
        async fn select_outbound(
            &self,
            request: tonic::Request<super::SelectOutboundRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
        /// Measures without waiting; the delays come in the outbounds.
        async fn url_test(
            &self,
            request: tonic::Request<super::UrlTestRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
        /// Measures one outbound, and waits.
        async fn delay(
            &self,
            request: tonic::Request<super::UrlTestRequest>,
        ) -> std::result::Result<tonic::Response<super::DelayReply>, tonic::Status>;
        async fn get_clash_mode_status(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::ClashModeStatus>, tonic::Status>;
        /// Server streaming response type for the SubscribeClashMode method.
        type SubscribeClashModeStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ClashMode, tonic::Status>,
            > + std::marker::Send
            + 'static;
        async fn subscribe_clash_mode(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<Self::SubscribeClashModeStream>, tonic::Status>;
        async fn set_clash_mode(
            &self,
            request: tonic::Request<super::ClashMode>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
        /// What the configuration sets that sail ignores or that is deprecated;
        /// read once, then gone.
        async fn get_deprecated_warnings(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Warnings>, tonic::Status>;
    }
    /// The instance, as the C ABI's control functions see it.
    #[derive(Debug)]
    pub struct StartedServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> StartedServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for StartedServer<T>
    where
        T: Started,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/sail.command.v1.Started/GetVersion" => {
                    #[allow(non_camel_case_types)]
                    struct GetVersionSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::UnaryService<super::Empty> for GetVersionSvc<T> {
                        type Response = super::Version;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(&mut self, request: tonic::Request<super::Empty>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as Started>::get_version(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetVersionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/SubscribeServiceStatus" => {
                    #[allow(non_camel_case_types)]
                    struct SubscribeServiceStatusSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::ServerStreamingService<super::Empty>
                        for SubscribeServiceStatusSvc<T>
                    {
                        type Response = super::ServiceStatus;
                        type ResponseStream = T::SubscribeServiceStatusStream;
                        type Future =
                            BoxFuture<tonic::Response<Self::ResponseStream>, tonic::Status>;
                        fn call(&mut self, request: tonic::Request<super::Empty>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Started>::subscribe_service_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubscribeServiceStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/GetServiceStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetServiceStatusSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::UnaryService<super::Empty> for GetServiceStatusSvc<T> {
                        type Response = super::ServiceStatus;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(&mut self, request: tonic::Request<super::Empty>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Started>::get_service_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetServiceStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/SubscribeLog" => {
                    #[allow(non_camel_case_types)]
                    struct SubscribeLogSvc<T: Started>(pub Arc<T>);
                    impl<T: Started>
                        tonic::server::ServerStreamingService<super::SubscribeLogRequest>
                        for SubscribeLogSvc<T>
                    {
                        type Response = super::Log;
                        type ResponseStream = T::SubscribeLogStream;
                        type Future =
                            BoxFuture<tonic::Response<Self::ResponseStream>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SubscribeLogRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as Started>::subscribe_log(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubscribeLogSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/ClearLogs" => {
                    #[allow(non_camel_case_types)]
                    struct ClearLogsSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::UnaryService<super::Empty> for ClearLogsSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(&mut self, request: tonic::Request<super::Empty>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as Started>::clear_logs(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ClearLogsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/SubscribeStatus" => {
                    #[allow(non_camel_case_types)]
                    struct SubscribeStatusSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::ServerStreamingService<super::IntervalRequest>
                        for SubscribeStatusSvc<T>
                    {
                        type Response = super::Status;
                        type ResponseStream = T::SubscribeStatusStream;
                        type Future =
                            BoxFuture<tonic::Response<Self::ResponseStream>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IntervalRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Started>::subscribe_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubscribeStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/GetTraffic" => {
                    #[allow(non_camel_case_types)]
                    struct GetTrafficSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::UnaryService<super::Empty> for GetTrafficSvc<T> {
                        type Response = super::Traffic;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(&mut self, request: tonic::Request<super::Empty>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as Started>::get_traffic(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetTrafficSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/SubscribeConnections" => {
                    #[allow(non_camel_case_types)]
                    struct SubscribeConnectionsSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::ServerStreamingService<super::IntervalRequest>
                        for SubscribeConnectionsSvc<T>
                    {
                        type Response = super::ConnectionEvents;
                        type ResponseStream = T::SubscribeConnectionsStream;
                        type Future =
                            BoxFuture<tonic::Response<Self::ResponseStream>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IntervalRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Started>::subscribe_connections(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubscribeConnectionsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/GetConnections" => {
                    #[allow(non_camel_case_types)]
                    struct GetConnectionsSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::UnaryService<super::Empty> for GetConnectionsSvc<T> {
                        type Response = super::Connections;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(&mut self, request: tonic::Request<super::Empty>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Started>::get_connections(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetConnectionsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/CloseConnection" => {
                    #[allow(non_camel_case_types)]
                    struct CloseConnectionSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::UnaryService<super::CloseConnectionRequest>
                        for CloseConnectionSvc<T>
                    {
                        type Response = super::CloseConnectionReply;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CloseConnectionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Started>::close_connection(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CloseConnectionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/CloseAllConnections" => {
                    #[allow(non_camel_case_types)]
                    struct CloseAllConnectionsSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::UnaryService<super::Empty> for CloseAllConnectionsSvc<T> {
                        type Response = super::CloseAllConnectionsReply;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(&mut self, request: tonic::Request<super::Empty>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Started>::close_all_connections(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CloseAllConnectionsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/SubscribeOutbounds" => {
                    #[allow(non_camel_case_types)]
                    struct SubscribeOutboundsSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::ServerStreamingService<super::IntervalRequest>
                        for SubscribeOutboundsSvc<T>
                    {
                        type Response = super::Outbounds;
                        type ResponseStream = T::SubscribeOutboundsStream;
                        type Future =
                            BoxFuture<tonic::Response<Self::ResponseStream>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IntervalRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Started>::subscribe_outbounds(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubscribeOutboundsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/GetOutbounds" => {
                    #[allow(non_camel_case_types)]
                    struct GetOutboundsSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::UnaryService<super::OutboundsRequest> for GetOutboundsSvc<T> {
                        type Response = super::Outbounds;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OutboundsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as Started>::get_outbounds(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetOutboundsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/SelectOutbound" => {
                    #[allow(non_camel_case_types)]
                    struct SelectOutboundSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::UnaryService<super::SelectOutboundRequest>
                        for SelectOutboundSvc<T>
                    {
                        type Response = super::Empty;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SelectOutboundRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Started>::select_outbound(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SelectOutboundSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/URLTest" => {
                    #[allow(non_camel_case_types)]
                    struct URLTestSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::UnaryService<super::UrlTestRequest> for URLTestSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UrlTestRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as Started>::url_test(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = URLTestSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/Delay" => {
                    #[allow(non_camel_case_types)]
                    struct DelaySvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::UnaryService<super::UrlTestRequest> for DelaySvc<T> {
                        type Response = super::DelayReply;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UrlTestRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move { <T as Started>::delay(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DelaySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/GetClashModeStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetClashModeStatusSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::UnaryService<super::Empty> for GetClashModeStatusSvc<T> {
                        type Response = super::ClashModeStatus;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(&mut self, request: tonic::Request<super::Empty>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Started>::get_clash_mode_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetClashModeStatusSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/SubscribeClashMode" => {
                    #[allow(non_camel_case_types)]
                    struct SubscribeClashModeSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::ServerStreamingService<super::Empty> for SubscribeClashModeSvc<T> {
                        type Response = super::ClashMode;
                        type ResponseStream = T::SubscribeClashModeStream;
                        type Future =
                            BoxFuture<tonic::Response<Self::ResponseStream>, tonic::Status>;
                        fn call(&mut self, request: tonic::Request<super::Empty>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Started>::subscribe_clash_mode(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubscribeClashModeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/SetClashMode" => {
                    #[allow(non_camel_case_types)]
                    struct SetClashModeSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::UnaryService<super::ClashMode> for SetClashModeSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ClashMode>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Started>::set_clash_mode(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetClashModeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Started/GetDeprecatedWarnings" => {
                    #[allow(non_camel_case_types)]
                    struct GetDeprecatedWarningsSvc<T: Started>(pub Arc<T>);
                    impl<T: Started> tonic::server::UnaryService<super::Empty> for GetDeprecatedWarningsSvc<T> {
                        type Response = super::Warnings;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(&mut self, request: tonic::Request<super::Empty>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Started>::get_deprecated_warnings(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetDeprecatedWarningsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    let mut response = http::Response::new(tonic::body::Body::default());
                    let headers = response.headers_mut();
                    headers.insert(
                        tonic::Status::GRPC_STATUS,
                        (tonic::Code::Unimplemented as i32).into(),
                    );
                    headers.insert(
                        http::header::CONTENT_TYPE,
                        tonic::metadata::GRPC_CONTENT_TYPE,
                    );
                    Ok(response)
                }),
            }
        }
    }
    impl<T> Clone for StartedServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "sail.command.v1.Started";
    impl<T> tonic::server::NamedService for StartedServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// Generated client implementations.
pub mod managed_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    /// What the tunnel process's host does: stopping and reloading go through
    /// it, as the system must know (the Network Extension's stop).
    #[derive(Debug, Clone)]
    pub struct ManagedClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ManagedClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ManagedClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ManagedClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<http::Request<tonic::body::Body>>>::Error:
                Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ManagedClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn stop_service(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/sail.command.v1.Managed/StopService");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sail.command.v1.Managed", "StopService"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn reload_service(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/sail.command.v1.Managed/ReloadService");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("sail.command.v1.Managed", "ReloadService"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod managed_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ManagedServer.
    #[async_trait]
    pub trait Managed: std::marker::Send + std::marker::Sync + 'static {
        async fn stop_service(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
        async fn reload_service(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
    }
    /// What the tunnel process's host does: stopping and reloading go through
    /// it, as the system must know (the Network Extension's stop).
    #[derive(Debug)]
    pub struct ManagedServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ManagedServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ManagedServer<T>
    where
        T: Managed,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/sail.command.v1.Managed/StopService" => {
                    #[allow(non_camel_case_types)]
                    struct StopServiceSvc<T: Managed>(pub Arc<T>);
                    impl<T: Managed> tonic::server::UnaryService<super::Empty> for StopServiceSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(&mut self, request: tonic::Request<super::Empty>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as Managed>::stop_service(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StopServiceSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/sail.command.v1.Managed/ReloadService" => {
                    #[allow(non_camel_case_types)]
                    struct ReloadServiceSvc<T: Managed>(pub Arc<T>);
                    impl<T: Managed> tonic::server::UnaryService<super::Empty> for ReloadServiceSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(&mut self, request: tonic::Request<super::Empty>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Managed>::reload_service(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReloadServiceSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    let mut response = http::Response::new(tonic::body::Body::default());
                    let headers = response.headers_mut();
                    headers.insert(
                        tonic::Status::GRPC_STATUS,
                        (tonic::Code::Unimplemented as i32).into(),
                    );
                    headers.insert(
                        http::header::CONTENT_TYPE,
                        tonic::metadata::GRPC_CONTENT_TYPE,
                    );
                    Ok(response)
                }),
            }
        }
    }
    impl<T> Clone for ManagedServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "sail.command.v1.Managed";
    impl<T> tonic::server::NamedService for ManagedServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
