//! The header, `include/sail.h`, is generated by cbindgen and committed:
//! these fail when it no longer says what the source exports, so it is
//! generated again (`cbindgen --config cbindgen.toml src/lib.rs -o
//! include/sail.h`, in sail-ffi).

use std::collections::BTreeSet;
use std::path::Path;

fn crate_dir() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

fn header() -> String {
    std::fs::read_to_string(crate_dir().join("include/sail.h")).unwrap()
}

/// The words starting with `prefix` in `text` that `is_item` takes.
fn names(text: &str, prefix: &str, is_item: impl Fn(&str, &str) -> bool) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    for line in text.lines() {
        let mut rest = line;
        while let Some(i) = rest.find(prefix) {
            let name: String = rest[i..]
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                .collect();
            let after = &rest[i + name.len()..];
            if is_item(line, after) {
                out.insert(name.clone());
            }
            rest = after;
        }
    }
    out
}

#[test]
fn the_header_declares_every_function_and_constant_exported() {
    let mut exported_fns = BTreeSet::new();
    let mut exported_consts = BTreeSet::new();
    for entry in std::fs::read_dir(crate_dir().join("src")).unwrap() {
        let source = std::fs::read_to_string(entry.unwrap().path()).unwrap();
        exported_fns.extend(names(&source, "sail_", |line, after| {
            line.contains("extern \"C\" fn") && after.starts_with('(')
        }));
        exported_consts.extend(names(&source, "SAIL_", |line, _| {
            line.trim_start().starts_with("pub const")
        }));
    }
    let header = header();
    let declared_fns = names(&header, "sail_", |line, after| {
        after.starts_with('(') && !line.trim_start().starts_with(['*', '/'])
    });
    let declared_consts = names(&header, "SAIL_", |line, _| line.starts_with("#define"));
    assert_eq!(declared_fns, exported_fns, "generate include/sail.h again");
    let mut declared_consts = declared_consts;
    declared_consts.remove("SAIL_H");
    assert_eq!(
        declared_consts, exported_consts,
        "generate include/sail.h again"
    );
    assert!(exported_fns.len() > 20);
}

/// Compiles the header with the system's C and C++ compilers, where there
/// are; skipped where there are none.
#[test]
fn the_header_compiles_as_c_and_as_cpp() {
    let header = crate_dir().join("include/sail.h");
    for (compiler, language, standard) in [("cc", "c", "-std=c11"), ("c++", "c++", "-std=c++17")] {
        let Ok(output) = std::process::Command::new(compiler)
            .args([
                standard,
                "-Wall",
                "-Werror",
                "-fsyntax-only",
                "-x",
                language,
            ])
            .arg(&header)
            .output()
        else {
            eprintln!(
                "{} not found: the header is not compiled as {}",
                compiler, language
            );
            continue;
        };
        assert!(
            output.status.success(),
            "{} {}: {}",
            compiler,
            language,
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
