#!/usr/bin/env python3
"""Regenerates the root certificate stores of sing-box's `certificate.store`
from the CCADB's public reports: `mozilla` and `chrome`, each with the
certificate authorities of China removed, as sing-box documents them.

    scripts/update-root-stores.py

writes sail/src/transport/tls/roots/{mozilla,chrome}.pem. Run it now and
then, as the browsers' lists change; the diff is the review.

- mozilla: Mozilla's included roots with the Websites trust bit. A root
  Mozilla distrusts for TLS after a date already past is left out: a list
  cannot say "only what it issued before", and trusting less is the safe
  side. sing-box's list keeps them, and its S/MIME-only roots too.
- chrome: the roots whose Google Chrome status is Included.
"""

import csv
import datetime
import io
import os
import sys
import urllib.request

CCADB = "https://ccadb.my.salesforce-sites.com"
OUT = os.path.join(os.path.dirname(__file__), "..", "sail", "src", "transport", "tls", "roots")

csv.field_size_limit(sys.maxsize)


def fetch(path):
    with urllib.request.urlopen(CCADB + path, timeout=300) as response:
        return list(csv.DictReader(io.StringIO(response.read().decode("utf-8"))))


def pem(value):
    value = value.strip().strip("'").strip()
    if not value.startswith("-----BEGIN CERTIFICATE-----"):
        raise ValueError("not a PEM certificate")
    return value.replace("\r\n", "\n")


def write(name, entries, source):
    today = datetime.date.today().isoformat()
    path = os.path.join(OUT, name + ".pem")
    with open(path, "w") as f:
        f.write("# The `%s` root store of sing-box's certificate.store, as sail has it.\n" % name)
        f.write("# Generated by scripts/update-root-stores.py on %s from %s.\n" % (today, source))
        f.write("# Certificate authorities of China removed. Do not edit by hand.\n")
        for label, cert in sorted(entries):
            f.write("\n# %s\n%s\n" % (label, cert))
    print("%s: %d roots" % (path, len(entries)))


def main():
    os.makedirs(OUT, exist_ok=True)
    today = datetime.date.today()

    china = {
        r["SHA-256 Fingerprint"].strip().upper()
        for r in fetch("/ccadb/AllCertificateRecordsCSVFormatv4")
        if r.get("Country", "").strip() == "China"
    }

    mozilla = []
    for r in fetch("/mozilla/IncludedCACertificateReportPEMCSV"):
        if "Websites" not in r["Trust Bits"]:
            continue
        if r["Geographic Focus"].strip() == "China":
            continue
        if r["SHA-256 Fingerprint"].strip().upper() in china:
            continue
        distrust = r["Distrust for TLS After Date"].strip()
        if distrust:
            try:
                after = datetime.datetime.strptime(distrust, "%Y.%m.%d").date()
            except ValueError:
                after = datetime.date.fromisoformat(distrust)
            if after <= today:
                continue
        mozilla.append((r["Common Name or Certificate Name"].strip(), pem(r["PEM Info"])))
    write("mozilla", mozilla, "the CCADB's Mozilla included report")

    chrome = []
    for r in fetch("/ccadb/RootCACertificatesIncludedByRSReportCSV"):
        if r["Google Chrome Status"].strip() != "Included":
            continue
        if r["SHA-256 Fingerprint"].strip().upper() in china:
            continue
        label = r.get("Subject", "").strip() or r["SHA-256 Fingerprint"]
        chrome.append((label, pem(r["X.509 Certificate (PEM)"])))
    write("chrome", chrome, "the CCADB's roots included by root store")


if __name__ == "__main__":
    main()
